//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Art_ID { get; set; }
        public string User_ID { get; set; }
        public string Title { get; set; }
        public int Category_ID { get; set; }
        public string Subject { get; set; }
        public string Price { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public string Size { get; set; }
        public string Medium { get; set; }
        public string Statement { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Status { get; set; }
        public string Cover_Pic_Path { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
