

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ArtGallery.Data.DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ArtBrowserDBContext : DbContext
{
    public ArtBrowserDBContext()
        : base("name=ArtBrowserDBContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<Artist> Artists { get; set; }

    public virtual DbSet<Institution> Institutions { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Announcement> Announcements { get; set; }

    public virtual DbSet<Art> Arts { get; set; }

    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<Exhibition> Exhibitions { get; set; }

    public virtual DbSet<FollowersInfo> FollowersInfoes { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<FeaturedPartner> FeaturedPartners { get; set; }

}

}

