
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ArtGallery.Data.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    public int EventId { get; set; }

    public string Title { get; set; }

    public string Location { get; set; }

    public string Address { get; set; }

    public string Statement { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<System.DateTime> Created { get; set; }

    public Nullable<System.DateTime> Modified { get; set; }

    public string ImagePath { get; set; }

    public Nullable<bool> DisplayInHomePage { get; set; }

    public Nullable<bool> IsExternal { get; set; }

    public string ExternalLink { get; set; }

}

}
