
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ArtGallery.Data.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class FollowersInfo
{

    public int Id { get; set; }

    public string Follower { get; set; }

    public string Following { get; set; }

    public System.DateTime Subscribed { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

}

}
