
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ArtGallery.Data.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Institution
{

    public int Institution_ID { get; set; }

    public string User_ID { get; set; }

    public string PhoneNumber { get; set; }

    public string Aboutus { get; set; }

    public string InstitutionType { get; set; }

    public string Profile_Pic { get; set; }

    public string Cover_Pic { get; set; }

    public string Location { get; set; }

    public string Price_Range { get; set; }

    public string Exhibition { get; set; }

    public string ContactUs { get; set; }

    public string Position { get; set; }

    public string OpeningTimes { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
