
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ArtGallery.Data.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Subscriber
{

    public int SubscriberId { get; set; }

    public bool IsActive { get; set; }

    public Nullable<System.DateTime> Created { get; set; }

    public Nullable<System.DateTime> Modified { get; set; }

    public string Email { get; set; }

}

}
